### ISSUE TITLE
Retain cycle?

### ISSUE THREAD

**Issue by gerchicov-bp** [lovesunstar/WKBridge#1]
Maybe I don't understand but the following code from example is extra:
```
webView.bridge.register({ [weak self] (parameters, _) in
            guard let strongSelf = self, let parameters = parameters else { return }
            strongSelf.alert(with: parameters["title"] as? String, message: parameters["message"] as? String)
        }, for: "alert")
```
and could be replaced with:
```
webView.bridge.register({ (parameters, _) in
            self.alert(with: parameters["title"] as? String, message: parameters["message"] as? String)
        }, for: "alert")
```

I red that Swift handles retain cycles by itself, doesn't it?

**Comment by lovesunstar** [comment]
This will definitely lead to a retain cycle.

viewcontroller ----> webview
webview ---> bridge
bridge ----> closure
closure ---> viewcontroller

Swift won't handle retain cycles by itself. And this would lead to a retain cycle if you use self in the closure.

You can use [unowned self] if you believe the webview and it's vc have the same life cycle.
